# --- DECORAZIONI ---
# 'yes' nasconde tutto. Se vuoi i bordi arrotondati usa 'titlebar-only'
hide_window_decorations titlebar-and-corners 
window_padding_width 20
remember_window_size no
initial_window_width  145c
initial_window_height 45c

# --- BORDI (Corretti) ---
window_border_width 2px
active_border_color #ffffff  # Azzurro per vederlo bene (o cambialo in #ffffff per bianco)
inactive_border_color #313244
draw_minimal_borders yes 

# --- TRASPARENZA ---
background_opacity 0.40
background_blur 7
background #000000
# --- FONT ---
font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        14.0

# --- COMPORTAMENTO ---
macos_quit_when_last_window_closed yes
macos_show_window_title_in window
